### ISSUE TITLE
Where can I get the BFM 2009?

### ISSUE THREAD

**Issue by nxsf8023** [unibas-gravis/basel-face-model-viewer#17]
In face, I neet to use the BFM 2009 now. So plz tell me where I can get it. Thanks!

**Comment by Andreas-Forster** [comment]
Just follow the link provided on the main page (README.md) right below the image, to get to the **PMM side**. There you will find the link under the menu _Data_.

For the next time, there is a [mailing list](https://groups.google.com/g/scalismo-faces) which I will add to the README. It would be nice also to know who is asking for help, on the one hand to make the community know each other and also to maybe better help you if we know from which direction you come to the project.
