### ISSUE TITLE
Is there are any way to generate multiple files and save the file?

### ISSUE THREAD

**Issue by spk921** [unibas-gravis/basel-face-model-viewer#2]
I am wondering is there are way to generate multiple files and save the file with this viewer?
Or is there are any version which I could use? 

I may modify this and compile it.  

https://github.com/unibas-gravis/basel-face-model-viewer/blob/master/src/main/scala/faces/apps/ModelViewer.scala 

Do you have any matlab version or python? 

I would like to create dataset for train machine learning.

**Comment by BernhardEgger** [comment]
Hi,
you can use scalismo-faces to generate model instances, render them and also save them into files.
https://github.com/unibas-gravis/scalismo-faces
The missing key for saving an image to a file is  PixelImageIO.write(rendering, new File("/tmp/filename"))

A tutorial on scalismo faces can be found here:
http://gravis.dmi.unibas.ch/PMM/lectures/fitting

**Comment by BernhardEgger** [comment]
That is maybe related to your question: https://github.com/unibas-gravis/parametric-face-image-generator
