### ISSUE TITLE
Can you tell me the file structure of bfm2019 or bfm2017?Thanks~

### ISSUE THREAD

**Issue by Luh1124** [unibas-gravis/basel-face-model-viewer#21]

**Comment by marcelluethi** [comment]
In bfm2109 and bfm2017 the models are stored in a hdf5 format. You can view the content of hdf5 files using for example [hdfview](https://www.hdfgroup.org/downloads/hdfview/). It is also simple to read and explore hdf5 files using python or Matlab

The shape part of the format is documented in this [google doc](https://docs.google.com/document/d/1ySwSsD-di8ez5WnViLl4VsYeRI-ggVa-HQRxG4kLjH4/edit?usp=sharing)

One you understand the overall structure, you will have no problems figuring out what the color parts mean and how it is stored.

**Comment by Luh1124** [comment]
Thank you. I have installed hdfview2.14.0 and can view its structure
