### ISSUE TITLE
How to open the file through the viewer in apple M1 chip?

### ISSUE THREAD

**Issue by georgesilver33** [unibas-gravis/basel-face-model-viewer#22]
I am using m1 macbook, and I got this error:

(base) eunjo@eunjoui-MacBookPro BFM % java -Xmx2g -jar model-viewer.jar   
Bundle jhdf5 (JHDF 5) does not support platform mac_aarch64

I am wondering if anyone solved this problem. Thank you!

**Comment by marcelluethi** [comment]
At the moment, the face model viewer does not yet support the M1 architecture. (support will be coming early next year). 
You can work around this problem by using a Java Runtime Environment for x86, which you can for example get from [adoptium](https://github.com/adoptium/adoptium/issues/180).
