### ISSUE TITLE
Any way to see images by entering the exact value of each PC?

### ISSUE THREAD

**Issue by georgesilver33** [unibas-gravis/basel-face-model-viewer#23]
Hi, 

I am currently exploring to generate multiple parametric images using this program.
What I want to do is to enter exact value number of each PC, rather than sliding up and down the sliders. 
Is there any way that I can generate images with exact values? 
Thank you for your help!

Sincerely, Jieun.

**Comment by BernhardEgger** [comment]
Hi,

the viewer currently does not support this functionality in the GUI.
You can however load an rps file in the GUI and in the RPS file you can set all the rendering parameters as well as the Model parameters (momo.shape or momo.color).
You can find an example rps file here:
https://github.com/unibas-gravis/scalismo-faces/blob/master/src/test/resources/renderParametersV4.rps

Best
Bernhard

**Comment by georgesilver33** [comment]
Hi, 

Thank you for your answer!
What do the three values indicate in _"shape": [-1.0, 0.5, -0.25],_ ?
<img width="277" alt="image" src="https://user-images.githubusercontent.com/77424650/203537193-3a79b85a-e2eb-4d84-a14d-88f7c0dd3abf.png">
Or is there any reference that I can refer to?

Thank you for your help!

Sincerely, Jieun.

**Comment by BernhardEgger** [comment]
Hi,

those values are the coefficients for the first 3 principal components for shape and color respectively.
Figure 4 on Page 13 shows a visualization of the first PCs of some public models
https://arxiv.org/pdf/1909.01815.pdf

Those parameters are also what you modify when you move the sliders

Best
Bernhard

**Comment by georgesilver33** [comment]
Hi, 

Now I understand! Then, what are the minimum and the maximum coefficient values of each dimension? 
I had differentiated coefficients several times, but I noticed that the the "maximal slider value" kept changing in the momo viewer depending on the input. I didn't understand what the maximal slider value does in changing the faces. 
I am so sorry for kept asking, but I could not find some references that delivers the specifics about the values in this program (or maybe I am not familiar with modeling stuff). If there is one, it would be grateful if you let me know. 

Also, I was manipulating values in the "example_config_controlled.json" file which is used in the parametric-image-generator program, but what do the mean and the variance indicate?  

"color-distribution": {
      "type": "gaussian",
      "mean": 0.0,
      "variance": 1.0
    },
    "shape-distribution": {
      "type": "gaussian",
      "mean": 0.0,
      "variance": 1.0
    },

I really appreciate your help! 

Sincerely
Jieun

**Comment by BernhardEgger** [comment]
Hi,

I suggest to have a closer look at the review paper I sent in my last message to get an understanding of 3DMMs
We also have a presentation covering the basics:
https://youtu.be/Q_DAEF0V_D0
and a presentation on the survey
https://www.youtube.com/watch?v=UGtIwWv1dds

The parameters theoretically go to infinity (as thei are Gaussian distributed - everything from -3 to 3 is however most likely, 0 would be the mean -1 and +1 would be one standard deviation away from the mean for that parameter.
The json file in the image generator defines the distribution according to which examples are generated. Here it is Gaussian with zero mean and standard deviation one - which corresponds to sample from the statistical prior. if you put a 3 there, you will get less likely samples or if you put uniform you can go wild 

Best
Bernhard

**Comment by georgesilver33** [comment]
Hi!

I have looked up relevant materials you've recommended, and thank you for the explanation!
I have one more question. I am trying to pick the number of dimensions to manipulate. I wonder whether there is PCA analysis result to refer to, in order to know how many dimensions explain how much variance of the total faces. For example, if the first 10 dimensions cover the 90% of the variance and then the latter dimensions does not drastically add the magnitude that the variance is explained, I would like to pick the 10 dimensions for face generation. 
Thank you for your help!

Sincerely, 
Jieun

**Comment by BernhardEgger** [comment]
Hi,

the variance of each component is saved in the model file and you can retrieve it easily with HDF view or via our scalismo libaries.

Best
Bernhard

**Comment by georgesilver33** [comment]
Hi again!

I see on the main page that said "the button load RPS will load rendering parameters from a .rps file (currently only shape, color and expression)". Is it still unavailable to manipulate head position through the rps file? Or is there any way that I can put the position value in this momo viewer? 
Thank you!

Best, 
Jieun

**Comment by BernhardEgger** [comment]
Hi,

this would need a slight adaptation of the source code.
You can however change the head pose manually or use the parametric image
generator instead to do this.

Best
Bernhard
--
0 1 0
0 0 1
1 1 1


Am Di., 20. Dez. 2022 um 04:23 Uhr schrieb georgesilver33 <
***@***.***>:

**Comment by georgesilver33** [comment]
Hi, 

Can I use designated shape/color dimension coefficients if i use parametric image generator? I found it hard to apply.
If there is any option that I can manipulate shape/color and pose values at the same time, I would like to know! 
Always thank you for your help!

Best, 
Jieun

**Comment by BernhardEgger** [comment]
Hi,

yes you can do that, but not without coding...

Best
Bernhard
--
0 1 0
0 0 1
1 1 1


Am Di., 20. Dez. 2022 um 09:02 Uhr schrieb georgesilver33 <
***@***.***>:

**Comment by georgesilver33** [comment]
Hi!

May I ask what do you mean by coding? I really want to know how..!
I have looked into 'example_config_random' files and found no way to manually write shape/color values...

Best,
Jieun

**Comment by BernhardEgger** [comment]
Hi,

with coding I mean programming. Changing the source code.

Best
Bernhard
--
0 1 0
0 0 1
1 1 1


Am Di., 20. Dez. 2022 um 09:13 Uhr schrieb georgesilver33 <
***@***.***>:

**Comment by georgesilver33** [comment]
Of course I knew coding equals programming. I am sorry if I misled you but I was asking which part should I adapt to get the result I want. I meant which source code.
I am very sorry for kept asking, and am really appreciative for sharing your program for free, but your materials need to be more user-friendly, adding more necessary information so that newcomers can understand what they should look at or do to know your program better. 
Thank you.

Jieun

**Comment by BernhardEgger** [comment]
Hi,

in this file here, you could change that not only the shape and color
parameters are overwritten, but also the pose
https://github.com/unibas-gravis/basel-face-model-viewer/blob/master/src/main/scala/faces/apps/ModelViewer.scala

With regards to your demand:
The released software is research software - so you cannot expect that
every detail is user-friendly and that everything is ready for newcomers.
We do however provide several tutorials on our software that help you
understand how it works and give a lot of information to newcomers.
This tutorial here is for example a good starting point to understand our
face framework
https://shapemodelling.cs.unibas.ch/web/probabilistic-face-fitting

Best
Bernhard
--
0 1 0
0 0 1
1 1 1


Am Di., 20. Dez. 2022 um 10:00 Uhr schrieb georgesilver33 <
***@***.***>:

**Comment by georgesilver33** [comment]
HI, 

Thank you so much for your answer. However, it is difficult to adjust scala codes to me. 
Hmm, it is a slightly different question, but do you have matlab version of the 2019 or 2017 model? 
I have found 01_MorphableModel.mat which is the matlab version model of 2009. 
Thank you for your help!

Sincerely, 
Jieun

**Comment by BernhardEgger** [comment]
Hi

no, a matlab version is not provided. However the scalismo files are in
hdf5 file format and matlab can read hdf5.

Best
Bernhard

georgesilver33 ***@***.***> schrieb am Di., 27. Dez. 2022,
02:12:

**Comment by georgesilver33** [comment]
Hi, 

In the matlab version of 2009, I found the "script_gen_random_head.m". I found that the 'load_model' function loads the pca variances, or mean values of each texture and shape model. Is it impossible to replace the 2009 model with the 2019 or 2017 model? I've actually tried by adjusting the 2009 original model using the 2019 model's values (only changing model.shapeMU, model.shapePC, model.shapeEV, model.texMU,   model.texPC,   model.texEV), but I failed to generate faces. I would appreciate if there is any other way I can adjust the model with the 2019 model values! 
Thank you so much.

Best, 
Jieun

**Comment by BernhardEgger** [comment]
Hi,

my guess is that you are missing the template somewhere. The template mesh
is part of the model an different between the two models.
An error message might be helpful

Best
Bernhard


georgesilver33 ***@***.***> schrieb am Fr., 30. Dez. 2022,
03:22:

**Comment by georgesilver33** [comment]
Thank you! There were differences in the model values between the 2019 version and the 2009 version.
I think I figured it out!
Thank you so much for your help. 

Best,
Jieun

**Comment by BernhardEgger** [comment]
Glad it worked out.
It might be valuable to report here what you learned such that future
researchers who find this issue can profit from it.

Best
Bernhard

georgesilver33 ***@***.***> schrieb am Fr., 6. Jan. 2023,
10:02:
